"""New Idea Development Page - Uses research-based questions and comprehensive document generation"""

import streamlit as st
import logging
from services.idea_service import idea_service
from models import IdeaDocument
from services.research_document_generator import research_document_generator


@st.dialog("Select Idea to Develop")
def select_idea_dialog(options):
    st.write("Choose an idea to proceed:")
    for label, idea in options.items():
        if st.button(label, key=f"sel_{idea.session_id}", use_container_width=True):
            st.session_state.selected_idea_key = label
            st.rerun()

def show():
    st.title("Idea Development")
    st.markdown("Refine your idea by answering AI-generated development questions based on research")
    
    # Get all ideas from the service
    ideas = idea_service.get_all_ideas()
    
    if not ideas:
        st.info("No ideas found in the catalog. Please submit an idea first.")
        return
    
    # Filter ideas that have development questions from research (stored in drafts)
    ideas_with_research = [
        idea for idea in ideas 
        if idea.drafts and 'development_questions' in idea.drafts and idea.drafts['development_questions']
    ]
    
    if not ideas_with_research:
        st.info("No ideas with research-based questions found. Please submit an idea with company research first.")
        return
    
    # Select idea to develop
    idea_options = {f"{idea.title} - {idea.metadata.get('company_name', 'Unknown Company') if idea.metadata else 'Unknown Company'}": idea for idea in ideas_with_research}
    
    if "selected_idea_key" not in st.session_state:
        st.session_state.selected_idea_key = None
        
    # If key is in session state but not in options (e.g. filtered out), reset
    if st.session_state.selected_idea_key and st.session_state.selected_idea_key not in idea_options:
        st.session_state.selected_idea_key = None

    col_sel1, col_sel2 = st.columns([3, 1])
    with col_sel1:
        if st.session_state.selected_idea_key:
            st.success(f"Selected: {st.session_state.selected_idea_key}")
        else:
            st.info("No idea selected.")
            
    with col_sel2:
        if st.button("Select Idea", use_container_width=True):
            select_idea_dialog(idea_options)
            
    selected_idea_key = st.session_state.selected_idea_key
    
    if selected_idea_key:
        selected_idea = idea_options[selected_idea_key]
        
        st.markdown("---")
        st.subheader(f"Developing: {selected_idea.title}")
        
        # Safely access metadata for company name
        company_name = "Unknown"
        if selected_idea.metadata and hasattr(selected_idea.metadata, 'get'):
            company_name = selected_idea.metadata.get('company_name', 'Unknown')
        
        st.write(f"**Company:** {company_name}")
        st.write(f"**Description:** {selected_idea.original_idea}")
        
        # Show comprehensive research context
        show_research_context(selected_idea)
        
        # Development questions form
        development_questions = selected_idea.drafts.get('development_questions', [])
        
        if not development_questions:
            st.warning("No development questions available for this idea.")
            return
        
        st.markdown("---")
        st.subheader("Development Questions")
        st.info("These questions were generated by AI based on comprehensive market and company research")
        
        # Initialize answers in session state
        if 'development_answers' not in st.session_state:
            # Pre-fill with existing answers if available
            existing_answers = selected_idea.drafts.get('development_answers', {})
            st.session_state.development_answers = existing_answers.copy() if existing_answers else {}
        
        # Display questions and collect answers
        answers = {}
        for question in development_questions:
            section = question.get('section', 'General')
            question_text = question.get('question', '')
            key = question.get('key', f"q_{len(answers)}")
            
            st.markdown(f"**{section}**")
            st.write(question_text)
            
            # Show research context hint for this question
            show_question_context_hint(question, selected_idea)
            
            # Text area for answer
            answer = st.text_area(
                f"Your answer for: {section}",
                value=st.session_state.development_answers.get(key, ''),
                key=key,
                height=150,
                placeholder=f"Provide your detailed answer based on the research context..."
            )
            
            answers[key] = answer
            st.markdown("---")
        
        # Save answers
        if st.button("Save Development Answers", type="primary"):
            if any(answers.values()):
                # Prepare update data for the service
                update_data = {
                    "drafts.development_answers": answers,
                    "status": "in_progress"
                }
                
                # Save to database using the correct service and ID
                if idea_service.update_idea(selected_idea.session_id, update_data):
                    st.success("Development answers saved successfully!")
                    st.session_state.development_answers = answers
                    
                    # Show next steps
                    st.info("""
                    **Next Steps:**
                    1. Continue refining your answers
                    2. Generate a comprehensive document
                    3. Submit for final review
                    """)
                else:
                    st.error("Failed to save development answers")
            else:
                st.warning("Please provide answers to at least some questions before saving.")
        
        # Show existing answers if available
        if selected_idea.drafts and 'development_answers' in selected_idea.drafts:
            st.markdown("---")
            st.subheader("Current Answers")
            existing_answers = selected_idea.drafts['development_answers']
            
            for question in development_questions:
                key = question.get('key')
                if key and key in existing_answers and existing_answers[key]:
                    st.markdown(f"**{question.get('section', 'General')}**")
                    st.write(existing_answers[key])
                    st.markdown("---")
        
        # Document generation
        st.markdown("---")
        st.subheader("Generate Professional Document")
        
        if st.button("Generate POC Proposal", type="secondary"):
            with st.spinner("Generating professional document with research insights..."):
                try:
                    # Generate document using research data and answers
                    document_data = prepare_document_data(selected_idea, answers)
                    docx_bytes = research_document_generator.generate_comprehensive_document(document_data)
                    
                    if docx_bytes:
                        st.session_state.generated_docx = docx_bytes
                        st.success("Document generated successfully!")
                    else:
                        st.error("Failed to generate document")
                        
                except Exception as e:
                    st.error(f"Error generating document: {str(e)}")
        
        # Download document if generated
        if 'generated_docx' in st.session_state and st.session_state.generated_docx:
            st.download_button(
                label="Download Document (.docx)",
                data=st.session_state.generated_docx,
                file_name=f"{selected_idea.title.replace(' ', '_')}_proposal.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            )

def show_research_context(idea: IdeaDocument):
    """Display comprehensive research context for the idea"""
    with st.expander("Research Context", expanded=True):
        if not idea.drafts:
            st.info("No research data available for this idea.")
            return

        company_research = idea.drafts.get('company_research')
        idea_research = idea.drafts.get('idea_research')
        roi_analysis = idea.drafts.get('roi_analysis')

        # Company research
        if company_research:
            st.markdown("### Company Research")
            if company_research.get('overview'):
                st.markdown("**Business Overview:**")
                st.write(company_research['overview'].get('business_model', 'N/A'))
            
            if company_research.get('financials'):
                st.markdown("**Financial Context:**")
                st.write(company_research['financials'].get('recent_performance', 'N/A'))
            
            if company_research.get('opportunities'):
                st.markdown("**Growth Opportunities:**")
                for opportunity in company_research['opportunities']:
                    st.write(f"- {opportunity}")
            
            if company_research.get('challenges'):
                st.markdown("**Business Challenges:**")
                for challenge in company_research['challenges']:
                    st.write(f"- {challenge}")
        
        # Market research
        if idea_research and idea_research.get('success'):
            st.markdown("### Market Research")
            if idea_research.get('market_overview'):
                st.markdown("**Market Overview:**")
                st.write(idea_research['market_overview'])
            
            if idea_research.get('existing_solutions'):
                st.markdown("**Existing Solutions:**")
                for solution in idea_research['existing_solutions'][:3]:
                    st.write(f"- **{solution.get('title', 'Solution')}**: {solution.get('description', '')}")
            
            if idea_research.get('competitors'):
                st.markdown("**Competitors:**")
                for competitor in idea_research['competitors'][:3]:
                    st.write(f"- **{competitor.get('name', 'Competitor')}**: {competitor.get('description', '')}")
        
        # ROI analysis
        if roi_analysis:
            st.markdown("### ROI Analysis")
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("ROI Score", f"{roi_analysis.get('roi_score', 0)}%")
            with col2:
                dev_cost = roi_analysis.get('estimated_development_cost', {})
                st.metric("Development Cost", f"${dev_cost.get('most_likely', 0):,}")
            with col3:
                time_to_roi = roi_analysis.get('estimated_time_to_roi', {})
                st.metric("Time to ROI", f"{time_to_roi.get('realistic', 0)} months")

def show_question_context_hint(question, idea: IdeaDocument):
    """Show relevant research context hints for each question"""
    section = question.get('section', '').lower()
    
    if not idea.drafts:
        return

    if 'company' in section and idea.drafts.get('company_research'):
        company_research = idea.drafts['company_research']
        if company_research.get('opportunities') or company_research.get('challenges'):
            with st.expander("Company Context Hint", expanded=False):
                if company_research.get('opportunities'):
                    st.write("**Relevant Opportunities:**")
                    for opp in company_research['opportunities'][:2]:
                        st.write(f"- {opp}")
                if company_research.get('challenges'):
                    st.write("**Relevant Challenges:**")
                    for challenge in company_research['challenges'][:2]:
                        st.write(f"- {challenge}")
    
    elif 'market' in section and idea.drafts.get('idea_research'):
        idea_research = idea.drafts['idea_research']
        if idea_research.get('success'):
            with st.expander("Market Context Hint", expanded=False):
                if idea_research.get('existing_solutions'):
                    st.write("**Existing Solutions:**")
                    for sol in idea_research['existing_solutions'][:2]:
                        st.write(f"- {sol.get('title', 'Solution')}")
                if idea_research.get('competitors'):
                    st.write("**Key Competitors:**")
                    for comp in idea_research['competitors'][:2]:
                        st.write(f"- {comp.get('name', 'Competitor')}")

def prepare_document_data(idea: IdeaDocument, answers):
    """Prepare comprehensive document data with research insights"""
    
    company_name = "Unknown Company"
    if idea.metadata and hasattr(idea.metadata, 'get'):
        company_name = idea.metadata.get('company_name', 'Unknown Company')

    document_data = {
        "title": idea.title,
        "company_name": company_name,
        "idea_description": idea.original_idea,
        "development_answers": answers,
        "company_research": idea.drafts.get('company_research') if idea.drafts else None,
        "market_research": idea.drafts.get('idea_research') if idea.drafts else None,
        "roi_analysis": idea.drafts.get('roi_analysis') if idea.drafts else None,
        "development_questions": idea.drafts.get('development_questions', []) if idea.drafts else []
    }
    
    return document_data

if __name__ == "__main__":
    show()
